# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
import pandas as pd
import re
from google.cloud import bigquery
import asyncio
# from app.cloudsql import CloudSQL
from cloudsql import CloudSQL
from dotenv import load_dotenv

load_dotenv()  

# Environment variables (set these in Cloud Run)
CLOUDSQL_INSTANCE_NAME = os.getenv('CLOUDSQL_INSTANCE_NAME')
CLOUDSQL_USER_NAME = os.getenv('CLOUDSQL_USER_NAME')
CLOUDSQL_PASSWORD = os.getenv('CLOUDSQL_PASSWORD')
CLOUDSQL_DB_NAME = os.getenv('CLOUDSQL_DB_NAME')
PROJECT_ID = os.getenv('PROJECT_ID')
BQ_DATASET = os.getenv('BQ_DATASET')
BQ_TABLE = os.getenv('BQ_TABLE')


async def fetch_current_prompt_data():
    sqlclient = CloudSQL()
    query = f'''SELECT
                    *
                FROM faq_embeddings
            '''

    # await sqlclient.connect(PG_HOST, PG_USER, PG_PASSWORD, PG_DATABASE)
    await sqlclient.connect(CLOUDSQL_INSTANCE_NAME, CLOUDSQL_USER_NAME, CLOUDSQL_PASSWORD, CLOUDSQL_DB_NAME)
    res = await sqlclient.execute(query, is_not_fetch=False)
    dataFrame = pd.DataFrame(res)
    return dataFrame

def read_new_prompt_data(filepath:str, sheet_name: str) -> pd.DataFrame:
    df = pd.read_excel(filepath, sheet_name=sheet_name)
    df = filter_data(df)
    return df

def filter_data(df: pd.DataFrame) -> pd.DataFrame:
    columns_to_keep = ['Type','Category', 'Prompt (Displayed on Prompt Library)','Response', 'Modify prompts','Status']
    columns_to_keep = ['Prompt (Displayed on Prompt Library)','Modify prompts']
    df = df[columns_to_keep]
    # df = df[df['Type'] == "Canned"]
    # df = df[df['Status'] == 'New']
    return df

async def insert_data_postgre(df: pd.DataFrame):
    sqlclient = CloudSQL()
    query = f'''
            INSERT INTO test_prompt_library (prompt, category, response, created_at, modified_at, starter_prompt, last_modified_by) 
            VALUES (:prompt, :category, :response, NOW(), NOW(), False, 50644164)
            '''
    query = f'''
        INSER INTO faq_embeddings (prompt, response)
        VALUES (:prompt, :response)
    '''
    await sqlclient.connect(CLOUDSQL_INSTANCE_NAME, CLOUDSQL_USER_NAME, CLOUDSQL_PASSWORD, CLOUDSQL_DB_NAME)
    for _, row in df.iterrows():
        params = {
            "prompt": row["Prompt (Displayed on Prompt Library)"],
            # "category": row["Category"],
            "response": row["Modify prompts"]
        }
        print(params)
        res = await sqlclient.execute(query, params, is_not_fetch=True)
        if not res: 
            print(f"Failed to insert row: {row}")
    
    print("Data inserted successfully.")
    return res

async def insert_or_update_data_postgre(df: pd.DataFrame, prompt_data: pd.DataFrame):
    sqlclient = CloudSQL()
    insert_query = '''
        INSERT INTO prompt_library (prompt, category, response, created_at, modified_at, starter_prompt, last_modified_by) 
        VALUES (:prompt, :category, :response, NOW(), NOW(), False, 50644164)
    '''
    insert_query = f'''
        INSERT INTO faq_embeddings (prompt, response)
        VALUES (:prompt, :response)
        '''
    update_query = '''
        UPDATE prompt_library
        SET response = :response, modified_at = NOW()
        WHERE prompt = :prompt
    '''
    update_query = f'''
        UPDATE faq_embeddings
        SET response = :response
        WHERE prompt = :prompt
    '''
    await sqlclient.connect(CLOUDSQL_INSTANCE_NAME, CLOUDSQL_USER_NAME, CLOUDSQL_PASSWORD, CLOUDSQL_DB_NAME)
    existing_prompts = set(prompt_data["prompt"].astype(str))
    for _, row in df.iterrows():
        prompt = str(row["Prompt (Displayed on Prompt Library)"])
        params = {
            "prompt": prompt,
            # "category": row["Category"],
            "response": row["Modify prompts"]
        }
        print("DF prompt:", prompt)
        print("Existing prompts:", existing_prompts)
        if prompt in existing_prompts:
            print(f"Updating: {prompt}")
            await sqlclient.execute(update_query, params, is_not_fetch=True)
        else:
            print(f"Inserting: {prompt}")
            await sqlclient.execute(insert_query, params, is_not_fetch=True)
    print("Insert/Update completed.")

async def main():
    sqlclient = CloudSQL()
    await sqlclient.connect(CLOUDSQL_INSTANCE_NAME, CLOUDSQL_USER_NAME, CLOUDSQL_PASSWORD, CLOUDSQL_DB_NAME)
    prompt_data = await fetch_current_prompt_data()
    df = read_new_prompt_data(filepath='new_prompts_to_test.xlsx', sheet_name='Prompt Library')
    # await insert_data_postgre(df)
    await insert_or_update_data_postgre(df, prompt_data)
    await sqlclient.close()


if __name__ == "__main__":
    asyncio.run(main())